SELECT DISTINCT
    'ALTER TABLE "'+fk.TABLE_SCHEMA+'"."'+FK.TABLE_NAME+'" ADD CONSTRAINT "'+c.CONSTRAINT_NAME+'"
            FOREIGN KEY ("'+cu.COLUMN_NAME+'") REFERENCES "'+pk.TABLE_SCHEMA+'"."'+pk.TABLE_NAME+'" ("'+PT.COLUMN_NAME+'");' AS [Output]
FROM
    INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS C
        INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS FK
                   ON C.CONSTRAINT_NAME = FK.CONSTRAINT_NAME
        INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS PK
                   ON C.UNIQUE_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
        INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE CU
                   ON C.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
        INNER JOIN (
        SELECT
            i1.TABLE_NAME,
            i2.COLUMN_NAME
        FROM
            INFORMATION_SCHEMA.TABLE_CONSTRAINTS i1
                INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE i2
                           ON i1.CONSTRAINT_NAME = i2.CONSTRAINT_NAME
        WHERE
                i1.CONSTRAINT_TYPE = 'PRIMARY KEY'
    ) PT
                   ON PT.TABLE_NAME = PK.TABLE_NAME
    AND fk.TABLE_SCHEMA+'.'+fk.TABLE_NAME NOT IN ({0})
    AND pk.TABLE_SCHEMA+'.'+pk.TABLE_NAME NOT IN ({0})
