SELECT 'COPY '+ t.TABLE_SCHEMA +'."'+ t.TABLE_NAME +'"('+STRING_AGG('"'+ c.COLUMN_NAME +'"',',') WITHIN GROUP (ORDER BY c.ORDINAL_POSITION) +') FROM ''{0}/'+ t.TABLE_SCHEMA +'.'+ t.TABLE_NAME +'.csv'' DELIMITER ''|'' CSV;
        UPDATE '+ t.TABLE_SCHEMA +'."'+t.TABLE_NAME+'" SET '+ STRING_AGG('"'+ c.COLUMN_NAME +'" = CAST(REPLACE(REPLACE(CAST("'+ c.COLUMN_NAME +'" AS CHARACTER VARYING), ''\n'', CHR(10)), ''\r'', CHR(13)) AS '+ et.PostgreSqlType +')',',') + ';' AS [Output]
FROM INFORMATION_SCHEMA.TABLES t
JOIN INFORMATION_SCHEMA.COLUMNS c ON t.TABLE_NAME = c.TABLE_NAME AND t.TABLE_SCHEMA = c.TABLE_SCHEMA
JOIN @EqualTypes et ON et.MsSqlType = c.DATA_TYPE
WHERE t.TABLE_SCHEMA + '.' + t.TABLE_NAME NOT IN ({1})
GROUP BY t.TABLE_SCHEMA, t.TABLE_NAME
